"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = __importDefault(require("fs"));
const promises_1 = __importDefault(require("fs/promises"));
const path_1 = __importDefault(require("path"));
const child_process_1 = require("child_process");
async function getInputs() {
    return {
        modelsPath: process.env.INPUT_MODELS_PATH || 'models',
        format: process.env.INPUT_FORMAT || 'html',
        githubToken: process.env.INPUT_GITHUB_TOKEN || process.env.GITHUB_TOKEN || '',
    };
}
function getGitHubContext() {
    const repo = process.env.GITHUB_REPOSITORY || '';
    const eventPath = process.env.GITHUB_EVENT_PATH || '';
    let prNumber = null;
    if (eventPath && fs_1.default.existsSync(eventPath)) {
        try {
            const event = JSON.parse(fs_1.default.readFileSync(eventPath, 'utf-8'));
            prNumber = event.pull_request?.number || null;
        }
        catch {
            // Silent fail - event might not be a PR event
        }
    }
    return { repo, prNumber, eventPath };
}
async function runAudit(modelsPath, format) {
    try {
        const workspace = process.env.GITHUB_WORKSPACE || process.cwd();
        const fullPath = path_1.default.join(workspace, modelsPath);
        // Run orvyen audit - __dirname is dist/action, so go up to dist/
        const cliPath = path_1.default.join(__dirname, '..', 'index.js');
        const cmd = `node "${cliPath}" "${fullPath}" --format json`;
        // Run without throwing on non-zero exit code (audit may return 1 if critical findings)
        try {
            (0, child_process_1.execSync)(cmd, { stdio: 'inherit' });
        }
        catch (error) {
            // Ignore exit code errors - we still want to read the report
            if (error.status !== 1) {
                throw error; // Re-throw if it's not the expected exit code
            }
        }
        // Read the generated JSON report
        const reportPath = path_1.default.join(workspace, '.orvyen', 'report.json');
        if (!(await fileExists(reportPath))) {
            console.error('Report not generated');
            return null;
        }
        const reportContent = await promises_1.default.readFile(reportPath, 'utf-8');
        const report = JSON.parse(reportContent);
        return report;
    }
    catch (error) {
        console.error('Failed to run audit:', error);
        return null;
    }
}
async function fileExists(filePath) {
    try {
        await promises_1.default.access(filePath);
        return true;
    }
    catch {
        return false;
    }
}
function formatCommentBody(report, reportPath) {
    const { summary } = report;
    const { critical, high, medium, low, total } = summary;
    if (total === 0) {
        return '✅ **Orvyen Audit Complete** — No findings! Your SQL architecture is clean.';
    }
    let comment = `## 🔍 Orvyen SQL Audit Report\n\n`;
    // Summary section
    comment += `### Summary\n`;
    comment += `- **Models analyzed**: ${report.project.modelsAnalyzed}\n`;
    comment += `- **Total findings**: ${total}\n\n`;
    // Severity breakdown
    if (critical > 0) {
        comment += `🔴 **Critical**: ${critical}\n`;
    }
    if (high > 0) {
        comment += `🟠 **High**: ${high}\n`;
    }
    if (medium > 0) {
        comment += `🟡 **Medium**: ${medium}\n`;
    }
    if (low > 0) {
        comment += `🟢 **Low**: ${low}\n`;
    }
    comment += `\n### Top Issues\n\n`;
    // Group by severity
    const bySeverity = {};
    for (const finding of report.findings) {
        if (!bySeverity[finding.severity]) {
            bySeverity[finding.severity] = [];
        }
        bySeverity[finding.severity].push(finding);
    }
    const severityOrder = ['critical', 'high', 'medium', 'low'];
    for (const severity of severityOrder) {
        const findings = bySeverity[severity] || [];
        if (findings.length === 0)
            continue;
        const icon = severity === 'critical' ? '🔴' : severity === 'high' ? '🟠' : severity === 'medium' ? '🟡' : '🟢';
        comment += `#### ${icon} ${severity.toUpperCase()}\n`;
        for (const finding of findings.slice(0, 5)) {
            comment += `- **${finding.model}**: ${finding.title}\n`;
        }
        if (findings.length > 5) {
            comment += `- ...and ${findings.length - 5} more\n`;
        }
        comment += '\n';
    }
    // Link to full report
    if (reportPath) {
        comment += `📊 [View Full Report](${reportPath})\n\n`;
    }
    comment += `---\n_Generated by [Orvyen](https://github.com/orvy/orvyen)_\n`;
    return comment;
}
async function postComment(repo, prNumber, githubToken, commentBody) {
    if (!repo || !prNumber || !githubToken) {
        console.log('Skipping comment post: missing repo, PR number, or token');
        return false;
    }
    const [owner, repoName] = repo.split('/');
    const url = `https://api.github.com/repos/${owner}/${repoName}/issues/${prNumber}/comments`;
    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${githubToken}`,
                'Content-Type': 'application/json',
                'Accept': 'application/vnd.github.v3+json',
                'User-Agent': 'Orvyen-Action',
            },
            body: JSON.stringify({ body: commentBody }),
        });
        if (!response.ok) {
            console.error(`Failed to post comment: ${response.status} ${response.statusText}`);
            return false;
        }
        console.log('✅ Posted comment to PR');
        return true;
    }
    catch (error) {
        console.error('Failed to post comment:', error);
        return false;
    }
}
function setOutput(name, value) {
    const outputFile = process.env.GITHUB_OUTPUT;
    if (outputFile) {
        fs_1.default.appendFileSync(outputFile, `${name}=${value}\n`);
    }
}
async function main() {
    console.log('🔍 Orvyen GitHub Action starting...\n');
    const inputs = await getInputs();
    const context = getGitHubContext();
    console.log(`Models path: ${inputs.modelsPath}`);
    console.log(`Format: ${inputs.format}`);
    console.log(`Repo: ${context.repo}`);
    console.log(`PR: ${context.prNumber || 'not a PR event'}\n`);
    // Run audit
    const report = await runAudit(inputs.modelsPath, inputs.format);
    if (!report) {
        console.error('❌ Audit failed');
        process.exit(1);
    }
    const { summary, project } = report;
    console.log(`✅ Audit complete: ${project.modelsAnalyzed} models, ${summary.total} findings\n`);
    // Set outputs
    setOutput('findings-count', String(summary.total));
    setOutput('critical-count', String(summary.critical));
    const reportPath = path_1.default.join(process.env.GITHUB_WORKSPACE || '', '.orvyen', 'report.html');
    setOutput('report-path', reportPath);
    // Post comment if PR
    if (context.prNumber) {
        const commentBody = formatCommentBody(report, `https://github.com/${context.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`);
        await postComment(context.repo, context.prNumber, inputs.githubToken, commentBody);
    }
    else {
        console.log('ℹ️ Not a PR event - skipping comment post');
    }
    // Exit with error if critical findings
    if (summary.critical > 0) {
        console.log(`\n⚠️ Critical findings detected. Exit code: 1`);
        process.exit(1);
    }
    console.log('\n✅ Action completed successfully');
    process.exit(0);
}
main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
});
//# sourceMappingURL=index.js.map